global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: echomind-java
    environment: production

scrape_configs:
  - job_name: echomind-java-app
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
          - echomind-java:8080
        labels:
          service: echomind-java

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
